poll_homepage:
    pattern:  /
    defaults: { _controller: PollPollBundle:Default:index }

poll_view_poll:
    pattern: /test_poll
    defaults: { _controller: PollPollBundle:Default:poll }

poll_create_poll:
    pattern: /create_poll
    defaults: { _controller: PollPollBundle:Default:createpoll }

poll_add_question:
    pattern: /poll/{poll_id}/add_question
    defaults: { _controller: PollPollBundle:Default:addquestion }
