poll_homepage:
    pattern:  /
    defaults: { _controller: PollPollBundle:Default:index }

poll_show_one:
    pattern: /poll/{poll_id}
    defaults: { _controller: PollPollBundle:Default:showpoll }

poll_show_all:
    pattern: /polls
    defaults: { _controller: PollPollBundle:Default:showpolls }

poll_create_poll:
    pattern: /create_poll
    defaults: { _controller: PollPollBundle:Default:createpoll }

poll_add_question:
    pattern: /poll/{poll_id}/add_question
    defaults: { _controller: PollPollBundle:Default:addquestion }

poll_delete_poll:
    pattern: /delete/poll/{poll_id}
    defaults: { _controller: PollPollBundle:Default:deletepoll }
