parameters:
#    poll_poll.example.class: Poll\PollBundle\Example

services:
#    poll_poll.example:
#        class: %poll_poll.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
